{{- if .Values.ingress.enabled -}}
{{- $fullName := include "outline.fullname" . -}}
{{- $webSvcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  number: {{ $webSvcPort }}
          {{- if .Values.services.collaboration }}
          - path: /collaboration
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-collaboration
                port:
                  number: 3002
          {{- end }}
{{- end }} 