apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.env.SECRET_KEY }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | b64enc }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if .Values.env.UTILS_SECRET }}
  UTILS_SECRET: {{ .Values.env.UTILS_SECRET | b64enc }}
  {{- else }}
  UTILS_SECRET: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if .Values.auth.discord.enabled }}
  DISCORD_CLIENT_ID: {{ .Values.auth.discord.clientId | default "" | b64enc }}
  DISCORD_CLIENT_SECRET: {{ .Values.auth.discord.clientSecret | default "" | b64enc }}
  DISCORD_SERVER_ID: {{ .Values.auth.discord.serverId | default "" | b64enc }}
  {{- end }}
  {{- if .Values.auth.google.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.auth.google.clientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.auth.slack.enabled }}
  SLACK_CLIENT_ID: {{ .Values.auth.slack.clientId | b64enc }}
  SLACK_CLIENT_SECRET: {{ .Values.auth.slack.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.auth.oidc.enabled }}
  OIDC_CLIENT_ID: {{ .Values.auth.oidc.clientId | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.smtp.enabled }}
  SMTP_HOST: {{ .Values.smtp.host | b64enc }}
  SMTP_PORT: {{ .Values.smtp.port | toString | b64enc }}
  {{- if .Values.smtp.username }}
  SMTP_USERNAME: {{ .Values.smtp.username | b64enc }}
  {{- end }}
  {{- if .Values.smtp.password }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc }}
  {{- end }}
  {{- if .Values.smtp.fromEmail }}
  SMTP_FROM_EMAIL: {{ .Values.smtp.fromEmail | b64enc }}
  {{- end }}
  {{- end }}
  {{- with .Values.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }} 