{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "outline.fullname" . }}-opensearch
  labels:
    {{- include "outline.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    - port: 9600
      targetPort: performance
      protocol: TCP
      name: performance
  selector:
    {{- include "outline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch
{{- end }}

{{- if and .Values.opensearch.enabled .Values.opensearch.dashboards.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "outline.fullname" . }}-opensearch-dashboards
  labels:
    {{- include "outline.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch-dashboards
spec:
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "outline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch-dashboards
{{- end }} 