{{- if .Values.storageInit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "outline.fullname" . }}-storage-init
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "outline.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: storage-init
    spec:
      serviceAccountName: {{ include "outline.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              # Add required labels and annotations for Helm to manage the storage class
              kubectl annotate storageclass local-path meta.helm.sh/release-name={{ .Release.Name }} meta.helm.sh/release-namespace={{ .Release.Namespace }} --overwrite
              kubectl label storageclass local-path app.kubernetes.io/managed-by=Helm --overwrite
              echo "StorageClass labels and annotations updated"
{{- end }} 