{{- if .Values.storageClasses.adoptExisting }}
{{- /* Check if local-path storage class already exists */ -}}
{{- $localPathExists := false }}
{{- $microk8sHostpathExists := false }}
{{- range (lookup "storage.k8s.io/v1" "StorageClass" "" "").items }}
  {{- if eq .metadata.name "local-path" }}
    {{- $localPathExists = true }}
  {{- end }}
  {{- if eq .metadata.name "microk8s-hostpath" }}
    {{- $microk8sHostpathExists = true }}
  {{- end }}
{{- end }}

# This template patches existing storage classes with Helm labels and annotations
# so they can be managed by the release

{{- if $localPathExists }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: Helm
    {{- include "outline.labels" . | nindent 4 }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{- end }}

{{- if $microk8sHostpathExists }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: microk8s-hostpath
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: Helm
    {{- include "outline.labels" . | nindent 4 }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{- end }}

{{- end }} 