services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6380:6379"
    user: "redis:redis"
    restart: unless-stopped
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
    restart: unless-stopped

  proxy:
    image: caddy:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
