# Staging environment values for outline.
replicaCount:
  web: 1
  worker: 1
  collaboration: 1

# Enable storage class creation for K3s
storageClasses:
  create: true

# Image pull secrets for private registry
imagePullSecrets:
  - name: github-container-registry

# Authentication configuration
auth:
  discord:
    enabled: true
    # Credentials stored in Kubernetes secret

# Disable other authentication methods
auth.google.enabled: false
auth.slack.enabled: false
auth.oidc.enabled: false

# Resources for staging (smaller than production)
resources:
  web:
    limits:
      cpu: 1000m
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 1Gi
  worker:
    limits:
      cpu: 1000m
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 1Gi
  collaboration:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 512Mi

# Use smaller persistence sizes for staging
persistence:
  enabled: true
  size: 5Gi
  storageClass: "local-path" # K3s local-path provisioner

# Pod annotations for K3s integration
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"

postgresql:
  enabled: true
  primary:
    persistence:
      size: 4Gi
      storageClassName: "local-path" # K3s local-path provisioner
  auth:
    username: outline
    password: outline
    database: outline
    enablePostgresUser: true
    postgresPassword: outline

redis:
  enabled: true
  master:
    persistence:
      size: 4Gi
      storageClassName: "local-path" # K3s local-path provisioner
  auth:
    enabled: false

# Enable ingress for staging
ingress:
  enabled: true
  className: "nginx" # This matches our nginx ingress class
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/tls-acme: "true" # For cert-manager integration
  host: staging.ethyrial.wiki
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: outline-staging-tls

# Environment variables for staging
env:
  URL: "https://staging.ethyrial.wiki"
  DEBUG: "http,sql"
  LOG_LEVEL: "debug"
  ENABLE_UPDATES: false
  NODE_ENV: "production"
  FORCE_HTTPS: true
  RATE_LIMITER_ENABLED: true
  # S3 Storage configuration
  FILE_STORAGE: "s3"
  AWS_S3_UPLOAD_BUCKET_NAME: "ethyrial-wiki-staging"
  AWS_S3_UPLOAD_BUCKET_URL: "https://s3.eu-central-1.amazonaws.com"
  AWS_REGION: "eu-central-1"
  PGSSLMODE: "disable"

# Add host networking for compatibility
hostNetwork: false # Changed to false as we're using node ports

# Add DNS config for K3s
dnsConfig:
  nameservers:
    - 10.43.0.10 # K3s CoreDNS service IP
  searches:
    - ethyrial-staging.svc.cluster.local
    - svc.cluster.local
    - cluster.local

# Reference existing secrets (created according to README instructions)
existingSecrets:
  auth: "outline-auth"
  keys: "outline-keys"
  s3: "outline-s3"
